language: python
matrix:
  include:
  - python: 3.6
    env: TOX_ENV=py36
  - python: 3.8
    env: TOX_ENV=py38
  - python: 3.8
    env: TOX_ENV=lint
install:
- pip install tox
- pip install codecov
script:
- tox -e $TOX_ENV
after_success:
    - codecov
